# Generated by Django 4.1.7 on 2023-03-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Alt', 'Alternative'), ('Pop', 'Pop'), (
                'Rap', 'Hip-Hop/Rap'), ('Country', 'Country')], default='---------', max_length=8),
        ),
    ]
