# Generated by Django 4.1.7 on 2023-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_artist_slug_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Alt', 'Alternative'), ('Pop', 'Pop'), ('Rap', 'Hip-Hop/Rap'), ('Country', 'Country')], default='---------', max_length=8, null=True),
        ),
    ]
